services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-php_6
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://symfony:symfony@database:3306/symfony?serverVersion=8.0&charset=utf8mb4
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: symfony-mysql_6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: symfony-nginx_6
    restart: unless-stopped
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php

  node:
    image: node:18
    container_name: symfony-node_6
    working_dir: /app
    volumes:
      - .:/app
    command: ["tail", "-f", "/dev/null"]

volumes:

  db_data:
